import "./globals.css";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata:Metadata={
  title:"Next App",
  description:"Generated by create next app",
  keywords:"nextjs,react,typescript,tailwindcss",


}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="max-w-3xl mx-auto py-20">{children}</main>
      </body>
    </html>
  );
}
